language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
install:
  - 'ls frameworker'
  - 'git submodule update'
  - 'composer install'
  - 'composer update'
  
script: 'phpunit tests  --bootstrap "./bootstrap/autoload.php"'  
